steps:
- name: 'gcr.io/cloud-builders/go'
  args: ['install','-v']
  env: ['PROJECT_ROOT=app']
- name: 'gcr.io/cloud-builders/go'
  args: ['test']
  env: ['PROJECT_ROOT=app']  
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '.', '--tag=gcr.io/$PROJECT_ID/gceme:latest']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['apply','-f','k8s/production/standalone-production.yaml']
  
images: ['gcr.io/$PROJECT_ID/gceme:latest']
